name: Testes da Restful Booker API com Postman/Newman
run-name: ${{ github.actor }} just made a push to the repository
on: [push]
jobs:
  check-newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      #- uses: actions/checkout@master
      #- uses: matt-ball/newman-action@master
        with:
          node-version: '20'
          collection: Testes Restful Booker API.postman_collection.json
      - name: "Install newman"
        run: "npm install -g newman"
      - name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      - name: "Run tests"
        run: newman run collection -r htmlextra
      - name: Publish report
        with:
          file_path: './newman/htmlreport.html'
          file_name: 'newmanReport.html'
          file_type: 'html'
