name: Testes da Restful Booker API com Postman/Newman
run-name: ${{ github.actor }} just made a push to the repository
on: [push]
jobs:
  check-newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          collection: Testes Restful Booker API.postman_collection.json
      - 
        name: "Install newman"
        run: "npm install -g newman"
      - 
        name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      - run: "pwd"
  run-newman:
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Run tests"
        run: "newman run Testes Restful Booker API.postman_collection.json -r htmlextra --reporter-htmlextra-export htmlreport.html --reporter-htmlextra-darkTheme  > runreport1.html"
      - 
        name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
